networks: 
  external: 
    external: false
  internal: 
    internal: true
services:
  db:
    image: "redis:alpine"
    networks:
      - internal
    restart: unless-stopped
    volumes:
      - "./data:/data"
  website:
    build: "."
    depends_on:
      - db
    environment:
      - STORAGE_TYPE=redis
      - STORAGE_HOST=db
      - STORAGE_PORT=6379
      - STORAGE_DB=0
    networks:
      - internal
      - external
    ports:
      - "7777:7777"
    restart: unless-stopped
version: "3.0"