networks:
  internet:
    ipam:
      driver: default
      config:
        - subnet: "192.168.255.253/30"
    external: false
  private:
    ipam:
      driver: default
      config:
        - subnet: "192.168.255.246/29"
    internal: true
services:
  db:
    image: "redis:alpine"
    networks:
      - private
    restart: unless-stopped
    volumes:
      - "./data:/data"
  website:
    build: "."
    depends_on:
      - db
    environment:
      - STORAGE_TYPE=redis
      - STORAGE_HOST=db
      - STORAGE_PORT=6379
      - STORAGE_DB=0
    networks:
      - private
      - internet
    ports:
      - "7777:7777"
    restart: unless-stopped
version: "3.0"
