networks:
  internet:
    internal: false
  private:
    internal: true
  traefik:
    name: traefik-network
    external: true

services:
  db:
    image: "redis:alpine"
    networks:
      - private
    restart: unless-stopped
    volumes:
      - "./data:/data"
  website:
    build: "."
    depends_on:
      - db
    environment:
      - STORAGE_TYPE=redis
      - STORAGE_HOST=db
      - STORAGE_PORT=6379
      - STORAGE_DB=0
    networks:
      - private
      - internet
      - traefik
    labels:
    labels:
    # Enable traefik
      - traefik.enable=true
    # Routings
      - traefik.http.routers.hastebin.entrypoints=web, websecure
      - traefik.http.routers.hastebin.rule=Host(`bin.hzmi.xyz`)
    # SNI and Domains TLS stuffs
      - traefik.http.routers.hastebin.tls.domains[0].main=bin.hzmi.xyz
      - traefik.http.routers.hastebin.tls.domains[0].sans=hzmi.xyz
    # TLS Options
      - traefik.http.routers.hastebin.tls=true
      - traefik.http.routers.hastebin.tls.options=cloudflare@file
      - traefik.http.routers.hastebin.tls.certresolver=letsencrypt
    # Middleware
      - traefik.http.routers.hastebin.middlewares=cloudflare-real-ip@file
    restart: unless-stopped

    restart: unless-stopped

version: "3.0"
